#!/usr/bin/env python

import json
import pipes
import sys
import fileinput

def main(argv):
    config_json = json.load(open(argv[1], "r"))
    key_values = config_json["configuration"]
    secure_key_values = config_json["secure_configuration"]

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))