#! /bin/sh

# set -e

rm -rf /etc/nginx/nginx.conf
cp /usr/lib/tne-prototype/config/nginx/nginx.conf /etc/nginx/nginx.conf

mkdir -p /etc/nginx/conf.d
rm -rf /etc/nginx/conf.d/default.conf
cp /usr/lib/tne-prototype/config/nginx/site.conf /etc/nginx/conf.d/default.conf